export let docters = [
    {
      id: 1,
      name: "Dr. John Doe",
      specialization: "Cardiologist",
      degree: "MBBS, MD (Cardiology)",
      experience: "15 years",
      contact: "+91 9876543210",
      email: "johndoe@example.com",
      location: "Mumbai, India",
      image: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: 2,
      name: "Dr. Sarah Smith",
      specialization: "Dermatologist",
      degree: "MBBS, MD (Dermatology)",
      experience: "10 years",
      contact: "+91 8765432109",
      email: "sarahsmith@example.com",
      location: "Delhi, India",
      image: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      id: 3,
      name: "Dr. Rahul Mehta",
      specialization: "Neurologist",
      degree: "MBBS, DM (Neurology)",
      experience: "12 years",
      contact: "+91 9988776655",
      email: "rahulmehta@example.com",
      location: "Bangalore, India",
      image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
      id: 4,
      name: "Dr. Priya Kapoor",
      specialization: "Pediatrician",
      degree: "MBBS, MD (Pediatrics)",
      experience: "8 years",
      contact: "+91 9876543221",
      email: "priyak@example.com",
      location: "Chennai, India",
      image: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
      id: 5,
      name: "Dr. Aman Verma",
      specialization: "Orthopedic Surgeon",
      degree: "MBBS, MS (Orthopedics)",
      experience: "14 years",
      contact: "+91 8765432110",
      email: "amanverma@example.com",
      location: "Pune, India",
      image: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
      id: 6,
      name: "Dr. Neha Sharma",
      specialization: "Gynecologist",
      degree: "MBBS, MD (Gynecology)",
      experience: "9 years",
      contact: "+91 9988771122",
      email: "nehasharma@example.com",
      location: "Hyderabad, India",
      image: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
      id: 7,
      name: "Dr. Anil Gupta",
      specialization: "Oncologist",
      degree: "MBBS, DM (Oncology)",
      experience: "18 years",
      contact: "+91 8899776655",
      email: "anilgupta@example.com",
      location: "Kolkata, India",
      image: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
      id: 8,
      name: "Dr. Kavita Reddy",
      specialization: "Psychiatrist",
      degree: "MBBS, MD (Psychiatry)",
      experience: "11 years",
      contact: "+91 7766554433",
      email: "kavitareddy@example.com",
      location: "Ahmedabad, India",
      image: "https://randomuser.me/api/portraits/women/8.jpg",
    },
    {
      id: 9,
      name: "Dr. Sandeep Kulkarni",
      specialization: "General Surgeon",
      degree: "MBBS, MS (General Surgery)",
      experience: "16 years",
      contact: "+91 6655443322",
      email: "sandeepk@example.com",
      location: "Jaipur, India",
      image: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
      id: 10,
      name: "Dr. Ritu Verma",
      specialization: "ENT Specialist",
      degree: "MBBS, MS (ENT)",
      experience: "13 years",
      contact: "+91 5544332211",
      email: "rituverma@example.com",
      location: "Chandigarh, India",
      image: "https://randomuser.me/api/portraits/women/10.jpg",
    },
  ];
  