export const staff = {
staffPerformance: [
{
id: 1,
name: "Rahul Sharma",
role: "Hospital Administrator",
performanceScore: 95,
tasksCompleted: 50,
monthlyTarget: 55,
attendance: "99%",
remarks: "Excellent performance, exceeding expectations.",
},
{
id: 2,
name: "Aarti Kapoor",
role: "Receptionist",
performanceScore: 92,
tasksCompleted: 45,
monthlyTarget: 50,
attendance: "98%",
remarks: "Great job, meeting high standards.",
},
{
id: 3,
name: "Sandeep Verma",
role: "Medical Records Clerk",
performanceScore: 91,
tasksCompleted: 40,
monthlyTarget: 45,
attendance: "97%",
remarks: "Consistently performing well.",
},
{
id: 4,
name: "Priya Sharma",
role: "Head Nurse",
performanceScore: 90,
tasksCompleted: 38,
monthlyTarget: 42,
attendance: "96%",
remarks: "Good performance, keep it up.",
},
{
id: 5,
name: "Manish Tiwari",
role: "Billing Clerk",
performanceScore: 89,
tasksCompleted: 35,
monthlyTarget: 40,
attendance: "95%",
remarks: "Satisfactory work, room for improvement.",
},
{
id: 6,
name: "Ritu Joshi",
role: "Senior Nurse",
performanceScore: 88,
tasksCompleted: 34,
monthlyTarget: 38,
attendance: "94%",
remarks: "Needs improvement in task completion.",
},
{
id: 7,
name: "Anil Mehta",
role: "Pharmacist",
performanceScore: 94,
tasksCompleted: 48,
monthlyTarget: 52,
attendance: "99%",
remarks: "Excellent, continues to exceed targets.",
},
{
id: 8,
name: "Sunita Bansal",
role: "Lab Technician",
performanceScore: 93,
tasksCompleted: 44,
monthlyTarget: 50,
attendance: "98%",
remarks: "Strong performance with high efficiency.",
},
{
id: 9,
name: "Rajesh Yadav",
role: "Security Guard",
performanceScore: 92,
tasksCompleted: 42,
monthlyTarget: 48,
attendance: "97%",
remarks: "Well-performing, slight improvements needed.",
},
{
id: 10,
name: "Kavita Agarwal",
role: "Housekeeping Supervisor",
performanceScore: 91,
tasksCompleted: 40,
monthlyTarget: 45,
attendance: "96%",
remarks: "Consistently meets expectations.",
},
],
};
